env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - prettier
overrides: []
parserOptions:
  ecmaVersion: "latest"
  sourceType: module
plugins:
  - react
rules:
  quotes: [2, "double", "avoid-escape"]
  react/prop-types: 0
  react/jsx-filename-extension: 0
  react/react-in-jsx-scope: 0
  react/no-array-index-key: 0
  camelcase: 0
  import/prefer-default-export: 0
