# Generated by Django 3.0.6 on 2021-05-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='bert',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='compression',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='factual_consistency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='novelty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='rouge1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='rouge2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='rougeL',
            field=models.FloatField(default=0),
        ),
    ]
