# Generated by Django 3.0.6 on 2021-06-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_smodel_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smodel',
            name='group',
        ),
    ]
