# Generated by Django 3.0.6 on 2021-06-13 23:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_smodel_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Statistics Data')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dataset')),
                ('smodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SModel')),
            ],
        ),
        migrations.AddField(
            model_name='smodel',
            name='dataset',
            field=models.ManyToManyField(through='api.ModelDataset', to='api.Dataset'),
        ),
    ]
