# Generated by Django 3.0.6 on 2021-06-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_summary_entity_factuality'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='bi_gram_abs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='tri_gram_abs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='uni_gram_abs',
            field=models.FloatField(default=0),
        ),
    ]
