# Generated by Django 3.0.6 on 2021-06-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_modeldataset_hisogram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeldataset',
            old_name='hisogram',
            new_name='histogram',
        ),
    ]
