version: "3.7"

services:
  web:
    image: api:latest
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - web_root_data:/root/.local
      - static_volume:/app/static
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=secret
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_DATABASE=django
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
    depends_on:
      - db
    # restart: always
    command: ./boot.sh

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=django
    shm_size: "2gb"
    ports:
      - 127.0.0.1:5432:5432
    restart: always

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - static_volume:/usr/src/sumviz/static
    depends_on:
      - web

volumes:
  static_volume:
  web_root_data:
  postgres_data:
